---
title: "Brandon Boone"
runtime: shiny
---

<hr>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(shiny)
library(ggplot2)
library(readxl)
library(dplyr)
library(readr)
Master <- read_csv("Master.csv")

Master <- Master %>%
  select(PlateLocSide, PlateLocHeight, TaggedPitchType, Batter, PitchCall, BatterTeam, RelSpeed, BatterSide, Pitcher, PitcherTeam, SpinRate)

Master <- Master %>%
  filter(PitcherTeam == "APP_MOU")

x <- c(-.95,.95,.95,-.95,-.95)
z <- c(1.6,1.6,3.5,3.5,1.6)
sz <- data.frame(x, z)

```


```{r}

ui <- fluidPage(
    inputPanel(
    selectInput("data", "",
 choices = unique(Master$Pitcher))
  ),

  mainPanel(dataTableOutput("outtable"))
)

server <- function(input, output) {
  output$outtable <- renderDataTable({
    filter_df <- Master %>%
      filter(Pitcher == input$data)
data.frame(aggregate(cbind(RelSpeed, SpinRate) ~ TaggedPitchType, data = filter_df, mean))
  })
  


}

shinyApp(ui = ui, server = server)
```
