---
title: "Appalachian State Baseball Analytics"
---

**Last Updated:**  `r format(Sys.time(), "%A, %B %d, %Y")`
<hr>

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", comment = NA, warning = FALSE, message = FALSE)
library(readr)
library(dplyr)
library(stringr)
library(utils)
library(ggplot2)
library(kableExtra)
master <- read.csv("~/Appalachian State Baseball/Git Repositories/appstatebaseball/master.csv")
hitter <- master %>%
  filter(BatterTeam == "APP_MOU" | BatterTeam == "APP_PRA")
```

```{r Fastball Filter}
fb <- hitter %>%
  filter(TaggedPitchType == "Fastball")
fbvr <- range(fb$RelSpeed, na.rm = TRUE)
fbsr <- range(fb$SpinRate, na.rm = TRUE)
```

```{r Rel Speed Filter}
fbv <- fb %>%
  filter(!is.na(RelSpeed)) %>% 
  mutate(VELOCITY = case_when(RelSpeed >= 93.5 ~ "94 & ABOVE MPH",
                                  RelSpeed >= 92.5 & RelSpeed <= 93.4999 ~ "93 MPH",
                                  RelSpeed >= 91.5 & RelSpeed <= 92.4999 ~ "92 MPH",
                                  RelSpeed >= 90.5 & RelSpeed <= 91.4999 ~ "91 MPH",
                                  RelSpeed >= 89.5 & RelSpeed <= 90.4999 ~ "90 MPH",
                                  RelSpeed >= 88.5 & RelSpeed <= 89.4999 ~ "89 MPH",
                                  RelSpeed >= 87.5 & RelSpeed <= 88.4999 ~ "88 MPH",
                                  RelSpeed >= 86.5 & RelSpeed <= 87.4999 ~ "87 MPH",
                                  RelSpeed >= 85.5 & RelSpeed <= 86.4999 ~ "86 MPH",
                                  RelSpeed >= 84.5 & RelSpeed <= 85.4999 ~ "85 MPH",
                                  RelSpeed >= 83.5 & RelSpeed <= 84.4999 ~ "84 MPH",
                                  RelSpeed >= 82.5 & RelSpeed <= 83.4999 ~ "83 MPH",
                                  RelSpeed >= 81.5 & RelSpeed <= 82.4999 ~ "82 MPH",
                                  RelSpeed >= 80.5 & RelSpeed <= 81.4999 ~ "81 MPH",
                                  RelSpeed >= 79.5 & RelSpeed <= 80.4999 ~ "80 MPH",
                                  RelSpeed >= 78.5 & RelSpeed <= 79.4999 ~ "79 MPH",
                                  RelSpeed >= 77.5 & RelSpeed <= 78.4999 ~ "78 MPH",
                                  RelSpeed >= 76.5 & RelSpeed <= 77.4999 ~ "77 MPH",
                                  RelSpeed >= 75.5 & RelSpeed <= 76.4999 ~ "76 MPH",
                                  RelSpeed >= 74.5 & RelSpeed <= 75.4999 ~ "75 MPH",
                                  RelSpeed <= 74.4999 ~ "74 & BELOW MPH"))

fbv_stats <- fbv %>%
  group_by(VELOCITY) %>%
  summarize(s = sum(str_count(PlayResult, "Single")),
            do = sum(str_count(PlayResult, "Double")),
            t = sum(str_count(PlayResult, "Triple")),
            hr = sum(str_count(PlayResult, "HomeRun")),
            hit = sum(s + do + t + hr),
            inpl = sum(str_count(PitchCall, "InPlay")),
            bb = sum(str_count(KorBB, "Walk")),
            hbp = sum(str_count(PitchCall, "HitByPitch")),
            walk = sum(hbp + bb),
            sac = sum(str_count(PlayResult, "Sacrifice")),
            so = sum(str_count(KorBB, "Strikeout")),
            pa = inpl + walk + so,
            ab = pa - walk - sac,
            AVERAGE = sprintf("%.3f", hit / ab)) %>% 
            arrange(desc(VELOCITY))

knitr::kable(select(fbv_stats, VELOCITY, AVERAGE), format = "html", align = c("c","c")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<hr>