---
title: "Pitching"
runtime: shiny
---

<hr>

```{r Setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = FALSE, message = FALSE, warning = FALSE)

library(shiny)
library(ggplot2)
library(readxl)
library(dplyr)
library(readr)
library(plotly)

Master <- read_csv("Master.csv", col_types = cols(Date = col_date(format = "%m/%d/%Y")))


Master <- Master %>%
  filter(PitcherTeam == "APP_MOU" | PitcherTeam == "APP_PRA")

x <- c(-.95,.95,.95,-.95,-.95)
z <- c(1.6,1.6,3.5,3.5,1.6)
sz <- data.frame(x, z)
Master$Bearing <- ((Master$Bearing * -1) + 90)*pi/180
Master$x <- Master$Distance*cos(Master$Bearing)
Master$y <- Master$Distance*sin(Master$Bearing)
bases <- data.frame(xa = c(0, 90/sqrt(2), 0, -90/sqrt(2), 0, rep(0)),
ya = c(0, 90/sqrt(2), 2 * 90/sqrt(2), 90/sqrt(2), 0, rep(0)))
```


```{r}

ui <- fluidPage(inputPanel(
  selectInput("data", "", choices = unique(Master$Pitcher)),
  dateRangeInput("date","", format = "mm-dd-yyyy", start = Sys.Date() - 175, end = Sys.Date()),
  checkboxGroupInput("batter", label = ("Batter Side"),
                     choices = unique(Master$BatterSide), selected = c("Right", "Left"))
  ),

  mainPanel(plotlyOutput("outplot"),dataTableOutput("outtable"))
)

server <- function(input, output) {

  output$outplot <- renderPlotly({
  filter_df <- Master %>%
    filter(Pitcher == input$data) %>%
    filter(Date >= input$date[1] & Date <= input$date[2]) %>%
    filter(BatterSide %in% input$batter) %>%
    filter(!PlayResult == "Undefined" & !PlayResult == "Sacrifice")
  
 p <-  ggplot(bases, aes(x = xa, y = ya)) + 
  geom_path() + 
  geom_point(data = filter_df, x = filter_df$x, y = filter_df$y, 
             aes(color = factor(filter_df$PlayResult), 
                 text = paste("Exit Speed: ", ExitSpeed, 
                               "<br> Distance: ", Distance,
                               "<br> Launch Angle: ", Angle))) + 
  geom_segment(x = 0, xend = -233.35, y = 0, yend = 233.35) +
  geom_segment(x = -233.35, xend = -160.59, y = 233.35, yend = 340) + 
  geom_segment(x = -160.59, xend = -49.36, y = 340, yend = 401.98) +
  geom_segment(x = -49.36, xend = 49.36, y = 401.98, yend = 401.98) +
  geom_segment(x = 49.36, xend = 157.67, y = 401.98, yend = 338.05) +
  geom_segment(x = 157.67, xend = 229.81, y = 338.05, yend = 229.81) +
  geom_segment(x = 229.81, xend = 0, y = 229.81, yend = 0) +
  xlim(-250, 250) + ylim(-10, 500) +
  theme(axis.line = element_blank(),
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      panel.background = element_blank(),
      panel.border = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      plot.background = element_blank(),
      legend.title = element_blank()) +
  coord_equal() +
    ggtitle("Hits Against Pitcher By Batter Side") +
  scale_color_discrete(limits = c("Single" ,"Double", "Triple", "HomeRun", "Out", "FieldersChoice", "Error"))
ggplotly(p, tooltip = "text")
  })
  
output$outtable <- renderDataTable({
  filter_df <- Master %>%
    filter(Pitcher == input$data) %>%
    filter(Date >= input$date[1] & Date <= input$date[2]) %>%
    filter(BatterSide %in% input$batter)

data.frame(aggregate(cbind(RelSpeed, SpinRate) ~ TaggedPitchType, data = filter_df, mean))
  })

}

shinyApp(ui = ui, server = server)
```

<hr>